//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "messages")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub session_id: Option<i32>,
	pub user_id: Option<i32>,
	pub role: Option<String>,
	#[sea_orm(column_type = "Text")]
	pub content: String,
	pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::sessions::Entity",
		from = "Column::SessionId",
		to = "super::sessions::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Sessions,
	#[sea_orm(
		belongs_to = "super::users::Entity",
		from = "Column::UserId",
		to = "super::users::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Users,
}

impl Related<super::sessions::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Sessions.def()
	}
}

impl Related<super::users::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Users.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
